services:
  dotnet-app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dev_dotnet
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
        - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    command: dotnet watch run --no-launch-profile --non-interactive

  tailwind-watcher:
    image: node:20
    container_name: dev_tailwind
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run watch:css"